name: 1st_workflow
on:
  workflow_dispatch:
  push:

run-name: ${{ github.actor }}
permissions:
  id-token: write
  contents: read
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 5188b71c-c65e-44f8-bcf6-e138f75658f8 #${{secrets.AZURE_CLIENT_ID}}
          tenant-id: 5642c8d6-0058-4d89-9a83-3f5de4d280b6 #${{secrets.AZURE_TENANT_ID}}
          subscription-id: b0805f22-5464-4af2-968e-fabac43ebd20 #${{secrets.AZURE_SUBSCRIPTION_ID}}


      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        id: Init
        run: terraform init
        working-directory: Infra/

      - name: Terraform fmt
        id: Fmt
        run: terraform fmt
        working-directory: Infra/

      - name: Terraform Validate
        id: Validate
        run: terraform validate
        working-directory: Infra/

      - name: Terraform Plan
        id: Plan
        run: terraform plan -no-color -input=false
        #continue-on-error: true
        working-directory: Infra/
        
  
      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve
        working-directory: Infra/
        
        
